### ISSUE TITLE
Use a class

### ISSUE THREAD

**Issue by martoio** [rytow1326/prj-rev-bwfs-dasmoto#5]
```css
.price{
    color: blue;
}
```
Don't make extra work for yourself, use classes the right way. 
https://github.com/rytow1326/prj-rev-bwfs-dasmoto/blob/1d660f77c5be38b8d9e6f1d363fc8076d73292b3/ArtsCrafts/resources/index.css#L20
